server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
    gateway:
      discovery:
        locator:
          enable: true
