spring:
  application:
    name: bankGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clientService
          uri: lb://clientService
          predicates:
            - Path=/clients/**
        - id: accountsService
          uri: lb://accountsService
          predicates:
            - Path=/accounts/**
        - id: transactionsService
          uri: lb://transactionsService
          predicates:
            - Path=/transactions/**
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8888

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"