server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/B1nast1c/NTTBank.git
          default-label: "main"
  security:
    user:
      name: root
      password: s3cr3t
